-- 1) Liste a quantidade de cidades por região
SELECT REGIAO.NOME, COUNT(CIDADE.NOME) AS Quantidade
FROM REGIAO
LEFT JOIN UF
ON REGIAO.ID = UF.IDREGIAO
LEFT JOIN CIDADE
ON UF.ID = CIDADE.IDUF
GROUP BY REGIAO.NOME;

-- 2) Lista a quantidade de clientes por UF, ordene por quantidade
SELECT CIDADE.IDUF, COUNT(CLIENTE.ID)
FROM CLIENTE
INNER JOIN CLIENTEENDERECO CLIEND
ON CLIENTE.ID = CLIEND.IDCLIENTE
INNER JOIN CIDADE
ON CLIEND.IDCIDADE = CIDADE.ID
GROUP BY CIDADE.IDUF
ORDER BY COUNT(CLIENTE.ID);

-- 2.1) >> Considere apenas as cidades ES, RJ e SC.
SELECT CIDADE.IDUF, COUNT(CLIENTE.ID)
FROM CLIENTE
INNER JOIN CLIENTEENDERECO CLIEND
ON CLIENTE.ID = CLIEND.IDCLIENTE
INNER JOIN CIDADE
ON CLIEND.IDCIDADE = CIDADE.ID
WHERE CIDADE.IDUF IN ("ES", "RJ", "SC")
GROUP BY CIDADE.IDUF
ORDER BY COUNT(CLIENTE.ID);

-- 3) Liste todos os clientes que tenha "sol" e "nova" no nome da rua de seu endereço
SELECT CLIENTE.NOME, CLIEND.NOMERUA
FROM CLIENTE
INNER JOIN CLIENTEENDERECO CLIEND
ON CLIENTE.ID = CLIEND.IDCLIENTE
WHERE CLIEND.NOMERUA LIKE "%sol%"
OR CLIEND.NOMERUA LIKE "%nova%";
