-- 1) Liste a quantidade de cidades por região
SELECT REGIAO.NOME, COUNT(CIDADE.NOME) AS Quantidade
FROM REGIAO
LEFT JOIN UF
ON REGIAO.ID = UF.IDREGIAO
LEFT JOIN CIDADE
ON UF.ID = CIDADE.IDUF
GROUP BY REGIAO.NOME;

-- 2) Lista a quantidade de clientes por UF, ordene por quantidade
-- >> Considere apenas as cidades ES, RJ e SC.
SELECT CIDADE.IDUF AS UF, COUNT(CLIENTE.ID) AS QuantidadeCliente
FROM CLIENTE
INNER JOIN CLIENTEENDERECO CLIEND
ON CLIENTE.ID = CLIEND.IDCLIENTE
INNER JOIN CIDADE
ON CLIEND.IDCIDADE = CIDADE.ID
WHERE CIDADE.IDUF IN ("ES", "RJ", "SC")
GROUP BY CIDADE.IDUF
ORDER BY COUNT(CLIENTE.ID);

-- 3) Liste todos os clientes que tenha "sol" e "nova" no nome da rua de seu endereço
SELECT CLIENTE.NOME, CLIEND.NOMERUA
FROM CLIENTE
INNER JOIN CLIENTEENDERECO CLIEND
ON CLIENTE.ID = CLIEND.IDCLIENTE
WHERE CLIEND.NOMERUA LIKE "%sol%"
OR CLIEND.NOMERUA LIKE "%nova%";

-- 4) Liste as encomendas onde o cliente está sem endereço cadastrado
SELECT ENC.ID, ENC.NOTAFISCAL, ENC.DATACADASTRO, ENC.SITUACAO, ENC.VALORFRETE, CLIEND.IDCLIENTE 
FROM ENCOMENDA ENC
LEFT JOIN CLIENTEENDERECO CLIEND
ON ENC.IDCLIENTE = CLIEND.IDCLIENTE
WHERE ISNULL(CLIEND.IDCLIENTE);

-- 5) Liste o nome dos clientes e suas respectivas cidades.
SELECT CLIENTE.NOME AS CLIENTE, CIDADE.NOME AS CIDADE
FROM CLIENTE
INNER JOIN CLIENTEENDERECO CLIEND
ON CLIENTE.ID = CLIEND.IDCLIENTE
INNER JOIN CIDADE
ON CLIEND.IDCIDADE = CIDADE.ID;

-- 6) Mostre a quantidade de encomendas feitas por cada cliente.
-- >> Considere apenas clientes que fizeram mais de um encomendas
SELECT CLIENTE.NOME AS CLIENTE, COUNT(ENC.ID) AS QUANTIDADE
FROM CLIENTE
INNER JOIN ENCOMENDA ENC
ON CLIENTE.ID = ENC.IDCLIENTE
GROUP BY CLIENTE.ID
HAVING COUNT(ENC.ID) > 1;

-- 7) Liste as encomendas com valor de frete acima de R$ 20,00, mostrando o nome do cliente, nome da transportadora e valor do frete.
SELECT CLIENTE.NOME AS Cliente, 
       TRANS.NOME AS Transportadora, 
       ENC.VALORFRETE as ValorDoFrete
FROM CLIENTE
INNER JOIN ENCOMENDA ENC
ON CLIENTE.ID = ENC.IDCLIENTE
INNER JOIN TRANSPORTADORA TRANS
ON ENC.IDTRANSPORTADORA = TRANS.ID
WHERE ENC.VALORFRETE > 20.0;

-- 8) Recupere os nomes das cidades que possuem mais de 5 clientes cadastrados.
