-- 1) Liste a quantidade de cidades por região
SELECT REGIAO.NOME, COUNT(CIDADE.NOME) AS Quantidade
FROM REGIAO
LEFT JOIN UF
ON REGIAO.ID = UF.IDREGIAO
LEFT JOIN CIDADE
ON UF.ID = CIDADE.IDUF
GROUP BY REGIAO.NOME;

-- 2) Lista a quantidade de clientes por UF, ordene por quantidade
-- >> Considere apenas as cidades ES, RJ e SC.
SELECT CIDADE.IDUF AS UF, COUNT(CLIENTE.ID) AS QuantidadeCliente
FROM CLIENTE
INNER JOIN CLIENTEENDERECO CLIEND
ON CLIENTE.ID = CLIEND.IDCLIENTE
INNER JOIN CIDADE
ON CLIEND.IDCIDADE = CIDADE.ID
WHERE CIDADE.IDUF IN ("ES", "RJ", "SC")
GROUP BY CIDADE.IDUF
ORDER BY COUNT(CLIENTE.ID);

-- 3) Liste todos os clientes que tenha "sol" e "nova" no nome da rua de seu endereço
SELECT CLIENTE.NOME, CLIEND.NOMERUA
FROM CLIENTE
INNER JOIN CLIENTEENDERECO CLIEND
ON CLIENTE.ID = CLIEND.IDCLIENTE
WHERE CLIEND.NOMERUA LIKE "%sol%"
OR CLIEND.NOMERUA LIKE "%nova%";

-- 4) Liste as encomendas onde o cliente está sem endereço cadastrado
SELECT ENC.ID, ENC.NOTAFISCAL, ENC.DATACADASTRO, ENC.SITUACAO, ENC.VALORFRETE, CLIEND.IDCLIENTE 
FROM ENCOMENDA ENC
LEFT JOIN CLIENTEENDERECO CLIEND
ON ENC.IDCLIENTE = CLIEND.IDCLIENTE
WHERE ISNULL(CLIEND.IDCLIENTE);

-- 5) Liste o nome dos clientes e suas respectivas cidades.
SELECT CLIENTE.NOME AS CLIENTE, CIDADE.NOME AS CIDADE
FROM CLIENTE
INNER JOIN CLIENTEENDERECO CLIEND
ON CLIENTE.ID = CLIEND.IDCLIENTE
INNER JOIN CIDADE
ON CLIEND.IDCIDADE = CIDADE.ID;

-- 6) Mostre a quantidade de encomendas feitas por cada cliente.
-- >> Considere apenas clientes que fizeram mais de um encomendas
SELECT CLIENTE.NOME AS CLIENTE, COUNT(ENC.ID) AS QUANTIDADE
FROM CLIENTE
INNER JOIN ENCOMENDA ENC
ON CLIENTE.ID = ENC.IDCLIENTE
GROUP BY CLIENTE.ID
HAVING COUNT(ENC.ID) > 1;

-- 7) Liste as encomendas com valor de frete acima de R$ 20,00, mostrando o nome do cliente, nome da transportadora e valor do frete.
SELECT CLIENTE.NOME AS Cliente, 
       TRANS.NOME AS Transportadora, 
       ENC.VALORFRETE as ValorDoFrete
FROM CLIENTE
INNER JOIN ENCOMENDA ENC
ON CLIENTE.ID = ENC.IDCLIENTE
INNER JOIN TRANSPORTADORA TRANS
ON ENC.IDTRANSPORTADORA = TRANS.ID
WHERE ENC.VALORFRETE > 20.0;

-- 8) Recupere os nomes das cidades que possuem mais de 5 clientes cadastrados.
SELECT CIDADE.NOME AS NomeCidade, COUNT(CLIEND.IDCLIENTE) AS QuantidadeClientes
FROM CIDADE
INNER JOIN CLIENTEENDERECO CLIEND
ON CIDADE.ID = CLIEND.IDCIDADE
GROUP BY CLIEND.IDCIDADE
HAVING COUNT(CLIEND.IDCLIENTE) > 5;

-- 9) Mostre os nomes dos clientes cadastrados nos últimos ano
SELECT NOME, DATACADASTRO
FROM CLIENTE
WHERE YEAR(DATACADASTRO) = 2024;

-- 10) Mostre o ranking de cliente que mais fizeram encomendas
SELECT CLIENTE.NOME, COUNT(ENC.ID)
FROM CLIENTE
INNER JOIN ENCOMENDA ENC
ON CLIENTE.ID = ENC.IDCLIENTE
GROUP BY ENC.IDCLIENTE
ORDER BY COUNT(ENC.ID) DESC;

-- 11) Monte o ranking de transportadora por valor total
SELECT TRANS.NOME AS Transportadora, SUM(ENC.VALORFRETE) AS ValorTotal
FROM TRANSPORTADORA TRANS
INNER JOIN ENCOMENDA ENC
ON TRANS.ID = ENC.IDTRANSPORTADORA
GROUP BY ENC.IDTRANSPORTADORA
ORDER BY SUM(ENC.VALORFRETE) DESC;

-- 12) Monte o ranking dos meses de cadastros dos clientes
SELECT DATE_FORMAT(DATACADASTRO, '%m/%Y') AS MesAno, COUNT(ID) AS Quantidade
FROM CLIENTE
GROUP BY MesAno
ORDER BY Quantidade DESC;

-- 13) Liste o valor de frete que cobrado por UF, Cidade e Transportadora nos últimos 2 anos.
-- Por UF
SELECT CIDADE.IDUF UF, SUM(ENC.VALORFRETE) SomaFrete 
FROM TRANSPORTADORA TRANS
INNER JOIN ENCOMENDA ENC 
ON TRANS.ID = ENC.IDTRANSPORTADORA
INNER JOIN CIDADE 
ON CIDADE.ID = TRANS.IDCIDADE
WHERE ENC.DATACADASTRO >= DATE_SUB(NOW(), INTERVAL 2 YEAR)
GROUP BY CIDADE.IDUF;

-- Por cidade
SELECT CIDADE.NOME Cidade, SUM(ENC.VALORFRETE) SomaFrete 
FROM TRANSPORTADORA TRANS
INNER JOIN ENCOMENDA ENC 
ON TRANS.ID = ENC.IDTRANSPORTADORA
INNER JOIN CIDADE 
ON CIDADE.ID = TRANS.IDCIDADE
WHERE ENC.DATACADASTRO >= DATE_SUB(NOW(), INTERVAL 2 YEAR)
GROUP BY CIDADE.NOME;

-- Por transportadora
SELECT TRANS.NOME Cidade, SUM(ENC.VALORFRETE) SomaFrete 
FROM TRANSPORTADORA TRANS
INNER JOIN ENCOMENDA ENC 
ON TRANS.ID = ENC.IDTRANSPORTADORA
INNER JOIN CIDADE 
ON CIDADE.ID = TRANS.IDCIDADE
WHERE ENC.DATACADASTRO >= DATE_SUB(NOW(), INTERVAL 2 YEAR)
GROUP BY TRANS.NOME;

-- 14) Liste a quantidade de frete por região
SELECT REGIAO.NOME, COUNT(ENC.ID) QTDFRETE
FROM ENCOMENDA ENC
INNER JOIN CLIENTEENDERECO CLIEND
ON ENC.IDCLIENTE = CLIEND.IDCLIENTE
INNER JOIN CIDADE
ON CLIEND.IDCIDADE = CIDADE.ID
INNER JOIN UF
ON CIDADE.IDUF = UF.ID
INNER JOIN REGIAO
ON UF.IDREGIAO = REGIAO.ID
GROUP BY REGIAO.NOME;

-- 15) Liste a idade de cada cliente, ordenando do mais velho para o mais jovem
