-- 1) Liste os seguintes dados
-- Número do pedido
-- Nome da Empresa que está comprando
-- Cidade da empresa que está comprando
-- Código e Nome do fornecedor (em uma única coluna)
-- Data de emissão
-- Codigo do produto
-- Descrição do produto
-- Quantidade total de itens
-- Valor total do pedido
-- Considerar apenas pedidos fechados (IDTSITUACAO)
SELECT 
    PEDI.NUMPEDIDO AS NumeroPedido,
    EMPR.NOMFANTASIA AS NomeEmpresa,
    CIDA.DSCCIDADE AS Cidade,
    FORN.CODFORNECEDOR || ' - ' || FORN.NOMFANTASIA AS Fornecedor,
    PEDI.DATEMISSAO AS DataEmissao,
    PEDITEM.CODPRODUTO AS CodigoProduto,
    PRODESC.DSCDESCRICAO AS DescricaoProduto,
    PEDITEM.QTDPRODUTOPEDIDO AS QuantidadeTotal,
    (PEDITEM.VALPRODUTOPEDIDO * PEDITEM.QTDPRODUTOPEDIDO) AS ValorTotalPedido
FROM PEDIDOTREINAMENTO PEDI
INNER JOIN GEN_EMPRESA EMPR ON PEDI.CODEMPRESA = EMPR.CODEMPRESA
INNER JOIN GEN_CIDADE CIDA ON EMPR.CODCIDADE = CIDA.CODCIDADE
INNER JOIN GEN_FORNECEDOR FORN ON PEDI.CODFORNECEDOR = FORN.CODFORNECEDOR
INNER JOIN PEDIDOTREINAMENTOITEM PEDITEM ON PEDI.NUMPEDIDO = PEDITEM.NUMPEDIDO
INNER JOIN GEN_PRODUTODESCRICAO PRODESC ON PEDITEM.CODPRODUTO = PRODESC.CODPRODUTO
WHERE PEDI.IDTSITUACAO = 'F';


-- 2) Liste a quantidade de Vidros e Retrovisores comprados nos três primeiros meses de 2024.
-- Mostrar os resultados agrupados por mês
SELECT TO_CHAR(PEDI.DATEMISSAO,'MM/YYYY') MES_ANO,
       COUNT(1) AS QUANTIDADE
FROM PEDIDOTREINAMENTO PEDI
INNER JOIN PEDIDOTREINAMENTOITEM PEDITEM 
ON PEDI.NUMPEDIDO = PEDITEM.NUMPEDIDO
AND PEDI.CODEMPRESA = PEDITEM.CODEMPRESA
INNER JOIN GEN_PRODUTODESCRICAO PDE
ON PDE.CODPRODUTO = PEDITEM.CODPRODUTO
WHERE PDE.CODTIPODESCRICAO = 1
AND (PDE.DSCDESCRICAO LIKE 'VID%' OR PDE.DSCDESCRICAO LIKE 'RET%')
AND PEDI.DATEMISSAO BETWEEN '01/01/2024' AND '31/03/2024'
GROUP BY TO_CHAR(PEDI.DATEMISSAO,'MM/YYYY');


-- 3) Liste a abreviação da empresa, sua cidade e sua UF, considere apenas empresas ativas
-- o campo IDTSITUACAO diz se a empresa está ativa, onde A = Ativa e I = Inativa.
SELECT 
    EMP.CODABREVIACAO AS AbreviacaoEmpresa,
    CID.DSCCIDADE AS Cidade,
    CID.CODUF AS UF
FROM GEN_EMPRESA EMP
INNER JOIN GEN_CIDADE CID ON EMP.CODCIDADE = CID.CODCIDADE
WHERE EMP.IDTSITUACAO = 'A';


-- 4) Liste a quantidade de empresas por UF.
SELECT CID.CODUF AS UF, COUNT(EMP.CODEMPRESA) AS QuantidadeCidades
FROM GEN_EMPRESA EMP
INNER JOIN GEN_CIDADE CID ON EMP.CODCIDADE = CID.CODCIDADE
GROUP BY CID.CODUF;


-- 5) Liste as empresas do RJ que estão ativas e que não fizeram nenhuma compra em 2024.
SELECT 
    EMP.NOMFANTASIA NomeEmpresa, 
    CID.DSCCIDADE AS Cidade, 
    CID.CODUF AS UF
FROM GEN_EMPRESA EMP
INNER JOIN GEN_CIDADE CID ON EMP.CODCIDADE = CID.CODCIDADE
LEFT JOIN PEDIDOTREINAMENTO PED
ON EMP.CODEMPRESA = PED.CODEMPRESA
AND PED.DATEMISSAO BETWEEN '01/01/2024' AND '01/01/2025'
WHERE EMP.IDTSITUACAO = 'A'
AND CID.CODUF = 'RJ'
AND PED.NUMPEDIDO IS NULL;


-- 6) Liste o número do pedido, data de emissão, abreviação da empresa, código do fornecedor e a descição do fornecedor.
-- Considerar apenas os pedidos dos fornecedores 408232 e 344306
-- odernar pela data de emissão
SELECT
    PED.NUMPEDIDO AS NumeroPedido,
    PED.DATEMISSAO AS DataEmissao,
    EMP.CODABREVIACAO AS AbreviacaoEmpresa,
    PED.CODFORNECEDOR AS CodigoFornecedor,
    FORN.DSCRAZAOSOCIAL AS DescricaoFornecedor
FROM PEDIDOTREINAMENTO PED
INNER JOIN GEN_EMPRESA EMP ON PED.CODEMPRESA = EMP.CODEMPRESA
INNER JOIN GEN_FORNECEDOR FORN ON PED.CODFORNECEDOR = FORN.CODFORNECEDOR
WHERE FORN.CODFORNECEDOR = 408232 OR FORN.CODFORNECEDOR = 344306
ORDER BY PED.DATEMISSAO;


-- 7) Usando a consulta 6 como base, considere apenas as empresas do pedido que são do ES (Espírito Santo).
-- Sugestão => Ligar a empresa com a cidade, a cidade com a UF e na UF filtrar por “ES”.
SELECT
    PED.NUMPEDIDO AS NumeroPedido,
    PED.DATEMISSAO AS DataEmissao,
    EMP.CODABREVIACAO AS AbreviacaoEmpresa,
    PED.CODFORNECEDOR AS CodigoFornecedor,
    FORN.DSCRAZAOSOCIAL AS DescricaoFornecedor,
    CID.CODUF AS UF
FROM PEDIDOTREINAMENTO PED
INNER JOIN GEN_EMPRESA EMP ON PED.CODEMPRESA = EMP.CODEMPRESA
INNER JOIN GEN_FORNECEDOR FORN ON PED.CODFORNECEDOR = FORN.CODFORNECEDOR
INNER JOIN GEN_CIDADE CID ON EMP.CODCIDADE = CID.CODCIDADE
AND CID.CODUF = 'ES'
WHERE FORN.CODFORNECEDOR = 408232 OR FORN.CODFORNECEDOR = 344306
ORDER BY PED.DATEMISSAO;


-- 8) Liste a quantidade de cidades por UF
SELECT CID.CODUF, COUNT(1) AS Quantidade
FROM GEN_CIDADE CID
GROUP BY CID.CODUF;


-- 9) Liste os seguintes campos
-- Número do Pedido
-- Empresa
-- Data Emissão
-- Quantidade total (será o total de itens do pedido → Usgestão: Somar a quantidade de itens da tabela  (PEDIDOTREINAMENTOITEM)
-- Valor total (será a soma de QTDPRODUTOPEDIDO * VALPRODUTOPEDIDO da tabela PEDIDOTREINAMENTOITEM)
SELECT 
    PED.NUMPEDIDO AS NumeroPedido,
    EMP.NOMFANTASIA AS Empresa,
    PED.DATEMISSAO AS DataEmissao,
    SUM(PEDITEM.QTDPRODUTOPEDIDO) AS QuantidadeTotal,
    SUM(PEDITEM.QTDPRODUTOPEDIDO * PEDITEM.VALPRODUTOPEDIDO) AS ValorTotal
FROM PEDIDOTREINAMENTO PED
INNER JOIN PEDIDOTREINAMENTOITEM PEDITEM ON PED.NUMPEDIDO = PEDITEM.NUMPEDIDO
INNER JOIN GEN_EMPRESA EMP ON PED.CODEMPRESA = EMP.CODEMPRESA 
GROUP BY 
    PED.NUMPEDIDO,
    EMP.NOMFANTASIA,
    PED.DATEMISSAO;


-- 10) Liste os fornecedores que não fizeram nenhuma venda nos últimos 2 anos
SELECT FORN.NOMFANTASIA AS Fornecedor, PED.NUMPEDIDO
FROM GEN_FORNECEDOR FORN
LEFT JOIN PEDIDOTREINAMENTO PED
ON FORN.CODFORNECEDOR = PED.CODFORNECEDOR
AND PED.DATEMISSAO >= ADD_MONTHS(SYSDATE, -24)
WHERE PED.NUMPEDIDO IS NULL;


-- 11) Liste a quantidade de produtos que cada fornecedor vendeu
SELECT 
    FORN.NOMFANTASIA AS Fornecedor,
    SUM(PEDITEM.QTDPRODUTOPEDIDO) AS QuantidadeProdutos
FROM PEDIDOTREINAMENTOITEM PEDITEM
INNER JOIN PEDIDOTREINAMENTO PED ON PEDITEM.NUMPEDIDO = PED.NUMPEDIDO
INNER JOIN GEN_FORNECEDOR FORN ON PED.CODFORNECEDOR = FORN.CODFORNECEDOR
GROUP BY FORN.CODFORNECEDOR, FORN.NOMFANTASIA;
