SELECT * FROM PEDIDOTREINAMENTO;

SELECT * FROM PEDIDOTREINAMENTOITEM;
 
SELECT * FROM GEN_FORNECEDOR;
 
SELECT * FROM GEN_EMPRESA;
 
SELECT * FROM GEN_CIDADE;
 
SELECT * FROM GEN_PRODUTO;
 
SELECT * FROM GEN_PRODUTODESCRICAO;